### ISSUE TITLE
FPGA DRAM First 512bit Is Not Zero After Reset

### ISSUE THREAD

**Issue by Xusine1131** [parsa-epfl/KnockoutKraken#66]

**Comment by UlisesLuzius** [comment]
Commit [c7246c4](https://github.com/parsa-epfl/KnockoutKraken/pull/81/commits/c7246c41e007c0cf91db026c1f56c55574cc2ef0) of pull request #81 fixed this issue.

The problem was that we need to clear the DRAM manually once we startup the FPGA.
