### ISSUE TITLE
CI Failed

### ISSUE THREAD

**Issue by Xusine1131** [parsa-epfl/KnockoutKraken#67]
Test `select-sort-15-threads` Infinite loop.

**Comment by UlisesLuzius** [comment]
This was due wrong implementation of `CreditQueueController` that resulted in bad pressure management for instruction and data TLB/Cache accesses.

The fix is in the pull request [tbd](https://github.com/parsa-epfl/KnockoutKraken/tree/fix-credits-and-inst)
