### ISSUE TITLE
Data Cache operations, potential missing synchronization

### ISSUE THREAD

**Issue by UlisesLuzius** [parsa-epfl/KnockoutKraken#68]
`void HELPER(dc_zva)(CPUARMState *env, uint64_t vaddr_in)` in `target/arm/helper-a64.c` modifies memory.

Ensure that page is transplanted correctly before call in `translation-a64.c`

**Comment by xusine** [comment]
The missing helpers:
- [x] LDAXR: pre_mem
- [x] AdvSIMD: pre and post
- [x] AdvSIMD: pre and post
- [x] SVE
